# This is a basic workflow to help you get started with Actions

name: Download JSON

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 7 * * 0-6"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: "Download today's JSON file"
        run: |
          echo -e -n "callback({mini:" > "$(TZ=UTC+4 date +%F).js"
          echo -n $(curl -s "https://www.nytimes.com/svc/crosswords/v6/puzzle/mini.json") >> "$(TZ=UTC+4 date +%F).js"
          echo -e -n ",connections:" >> "$(TZ=UTC+4 date +%F).js"
          curl -s "https://www.nytimes.com/svc/connections/v2/$(TZ=UTC+4 date +%F).json" >> "$(TZ=UTC+4 date +%F).js"
          echo -e -n ",spellingbee:" >> "$(TZ=UTC+4 date +%F).js"
          curl -s "https://www.nytimes.com/puzzles/spelling-bee" | echo -n $(grep -o -P '(?<=window\.gameData \= ).*?(?=\<\/script)') >> "$(TZ=UTC+4 date +%F).js"
          echo -e -n ",wordle:" >> "$(TZ=UTC+4 date +%F).js"
          curl -s "https://www.nytimes.com/svc/wordle/v2/$(TZ=UTC+4 date +%F).json" >> "$(TZ=UTC+4 date +%F).js"
          echo -e -n ",letterboxed:" >> "$(TZ=UTC+4 date +%F).js"
          curl -s "https://www.nytimes.com/puzzles/letter-boxed" | echo -n $(grep -o -P '(?<=window\.gameData \= ).*?(?=\<\/script)') >> "$(TZ=UTC+4 date +%F).js"
          echo -e -n ",tiles:" >> "$(TZ=UTC+4 date +%F).js"
          curl -s "https://www.nytimes.com/puzzles/tiles" | echo -n $(grep -o -P '(?<=window\.gameData \= ).*?(?=\<\/script)') >> "$(TZ=UTC+4 date +%F).js"
          echo -e -n ",strands:" >> "$(TZ=UTC+4 date +%F).js"
          curl -s "https://www.nytimes.com/svc/strands/v2/$(TZ=UTC+4 date +%F).json" >> "$(TZ=UTC+4 date +%F).js"
          echo -e -n ",sudoku:" >> "$(TZ=UTC+4 date +%F).js"
          curl -s "https://www.nytimes.com/puzzles/sudoku" | echo -n $(grep -o -P '(?<=window\.gameData \= ).*?(?=\<\/script)') >> "$(TZ=UTC+4 date +%F).js"
          echo -e -n "});" >> "$(TZ=UTC+4 date +%F).js"
      - name: Push
        run: |
          git config --global user.email "somebudyelse-ka@users.noreply.github.com"
          git config --global user.name "somebudyelse-ka"
          git add "$(TZ=UTC+4 date +%F).js"
          git commit -am "Update JSON"
          git push
